### ISSUE TITLE
Show toast if no internet connection

### ISSUE THREAD

**Issue by Grabli66** [RapidFingers/Translator#13]

**Comment by mkinitcpio** [comment]
Maybe better to use overlay bar with spinner when we haven't got internet connection? And disable all input possibilities while any connections not appear?
![image](https://user-images.githubusercontent.com/12542028/37245685-f816aa68-24ac-11e8-8155-76044fd4b668.png)

**Comment by mkinitcpio** [comment]
I didn't understand how overlaybar work, so toast would be better way for show a loss internet connection.
