### ISSUE TITLE
Feature Request: Add Slovak Language

### ISSUE THREAD

**Issue by jos-henson** [RapidFingers/Translator#32]
Hi there,

I really love your app, very clean and lightweight, but is there any way that you could possibly please add support for Slovak language.

I know it is a very simple minor thing that I can change myself and then build the app from source via a modification to GlobalSettings.vala (which I have done), but I quite like to obviously get updates via the App Center when you release them, rather than having to build it again from source each time you release new fixes.

If Slovak seems to 'obscure' for you, as obviously maybe you want to keep it simple and not support every single language out there, is there a way to possbily allow the users somehow to modify the GlobalSettings.vala file (or rather the outputs of the file once built) via the app itself and to add custom languages of their choosing?

Anyway, I promise to throw a few dollars/euros/whatever your currency is at you via the appcentre if you can make this happen! :-)

Thanks again for all your great work on this app!

**Comment by Grabli66** [comment]
Done

**Comment by jos-henson** [comment]
Hey,

Thanks so much for adding that in so quickly, just downloaded the update on the App store and it works great.

Quick question though - is there any way I can contribute/donate as promised for the app, because I really like it and appreciate how quickly you responded to my feature request! I tried uninstalling the app and reinstalling it via the app centre, but it was still just listed as 'free' with no way for me to donate...do you have an account on anything like patreon etc? 

Thanks again!

**Comment by Grabli66** [comment]
I can't recieve any donations from app center. Cause app center uses "stripe.com" for payment, and stripe does not work with my country.
Nevermind. It's free.

May be later i'll add simple html page on github with donate button.
