### ISSUE TITLE
Copy to clipboard button

### ISSUE THREAD

**Issue by Grabli66** [RapidFingers/Translator#46]

**Comment by camellan** [comment]
See pull request
![screen record from 2019-01-31 20 36 09](https://user-images.githubusercontent.com/7396198/52069902-1ee41980-2599-11e9-8a18-c7562c15280f.gif)

**Comment by Grabli66** [comment]
Я уже смотрел. Мне не очень нравится дизайн этих кнопок. На мой взгляд они занимают слишком много места. Но я пока не знаю как сделать лучше.

**Comment by camellan** [comment]
Согласен, жирноватые ) Но в работе очень удобно, не промахнёшься.

**Comment by camellan** [comment]
Так вроде посимпотичнее?
![2019-02-02 22 32 59](https://user-images.githubusercontent.com/7396198/52167835-c6e51880-273a-11e9-85a1-d45b9e46bde9.png)

**Comment by Grabli66** [comment]
Да. Так лучше. 
Сегодня посмотрю. Если всё нормально залью в master.
