### ISSUE TITLE
Segmentation error

### ISSUE THREAD

**Issue by camellan** [RapidFingers/Translator#49]
If the dictionary to find the meaning of the word "fund", the program crashes with the error:
** (com.github.rapidfingers.translator:15655): CRITICAL **: 20:21:45.384: dictionary_service_GetSpeechPart: assertion 's != NULL' failed

**Comment by camellan** [comment]
Исправил в последнем коммите

**Comment by Grabli66** [comment]
Очень хорошо. Спасибо.
