### ISSUE TITLE
Отказ от styleWindow()

### ISSUE THREAD

**Issue by camellan** [RapidFingers/Translator#56]
Предлагаю отказаться от использования styleWindow(). При светлой теме всё выглядит отлично. При тёмной как-то не очень...
![Снимок экрана от 2019-03-25 18 21 47](https://user-images.githubusercontent.com/7396198/54927602-e6731300-4f2b-11e9-969b-80d3fa5513c6.png)
![Снимок экрана от 2019-03-25 18 22 09](https://user-images.githubusercontent.com/7396198/54927608-ea069a00-4f2b-11e9-9568-6ce6a1fe26ef.png)

**Comment by Grabli66** [comment]
Это решается с помощью CSS. Исправлю

**Comment by Grabli66** [comment]
Fixed
